---
title: "Data_viz_1_astronaut"
output: html_document
date: "2022-11-26"
---

<font size ="5"><center> **Internet Users by Region**</center></font>

----

The waffle charts show the percentage of individuals using the Internet in 2019 in 6 regions. Data comes from [International Telecommunication Union](https://www.itu.int/en/ITU-D/Statistics/Pages/facts/default.aspx
).

**How to read the waffle chart** 

- There are 100 cells in each waffle chart, with each cell representing 1% of the population in each region.
- The colored cells represent the percentage of Internet users in each region

```{r message = FALSE, warning = FALSE, out.width = '100%', fig.align='center'}
library(waffle)
library(magrittr)
library(ggplot2)
library(cowplot)
text_color = "#737373"
font = "Avenir Next"
title_hjust = 0
caption_hjust = 1
world_internet <- data.frame(label = as.factor(c("part", "total")), africa = c(29, 71), americas = c(77, 23), arab = c(55,45), asia = c(45, 55), commonwealth = c(73, 27), europe = c(83, 17), world = c(51, 49)
)
africa <- ggplot(world_internet[,1:2], aes(fill = label, values = africa)) +
  geom_waffle(
    nrows = 10, 
    flip = TRUE,
    show.legend = FALSE,
    color = "white",
    size = 0.5,
    radius = unit(2, "pt")) +
  labs(title = "Africa",
       caption = "29%") +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  scale_fill_manual(values = c("#1f78b4", "#d9d9d9"))+
  coord_equal() +
  theme(plot.caption= element_text(family = font, color = "#1f78b4", size = 10, face = "bold", hjust = caption_hjust, margin = margin(t = 5)),
    plot.title = element_text(family = font, color = text_color, size = 14, face = "bold", hjust = title_hjust, margin = margin(b = 2))
  )
americas <- ggplot(world_internet[,1:3], aes(fill = label, values = americas)) +
  geom_waffle(
    nrows = 10, 
    flip = TRUE,
    show.legend = FALSE,
    color = "white",
    size = 0.5,
    radius = unit(2, "pt")) +
  labs(title = "Americas",
       caption = "77%") +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  scale_fill_manual(values = c("#33a02c", "#d9d9d9"))+
  coord_equal() +
  theme(plot.caption= element_text(family = font, color = "#33a02c", size = 10, face = "bold", hjust = caption_hjust, margin = margin(t = 5)),
    plot.title = element_text(family = font, color = text_color, size = 14, face = "bold", hjust = title_hjust, margin = margin(b = 2))
  )
arab <- ggplot(world_internet[,1:4], aes(fill = label, values = arab)) +
  geom_waffle(
    nrows = 10, 
    flip = TRUE,
    show.legend = FALSE,
    color = "white",
    size = 0.5,
    radius = unit(2, "pt")) +
  labs(title = "Arab States",
       caption = "55%") +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  scale_fill_manual(values = c("#6a3d9a", "#d9d9d9"))+
  coord_equal() +
  theme(plot.caption= element_text(family = font, color = "#6a3d9a", size = 10, face = "bold", hjust = caption_hjust, margin = margin(t = 5)),
    plot.title = element_text(family = font, color = text_color, size = 14, face = "bold", hjust = title_hjust, margin = margin(b = 2))
  )
asia <- ggplot(world_internet[,1:5], aes(fill = label, values = asia)) +
  geom_waffle(
    nrows = 10, 
    flip = TRUE,
    show.legend = FALSE,
    color = "white",
    size = 0.5,
    radius = unit(2, "pt")) +
  labs(title = "Asia & Pacific",
       caption = "45%") +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  scale_fill_manual(values = c("#b15928", "#d9d9d9"))+
  coord_equal() +
  theme(plot.caption= element_text(family = font, color = "#b15928", size = 10, face = "bold", hjust = caption_hjust, margin = margin(t = 5)),
    plot.title = element_text(family = font, color = text_color, size = 14, face = "bold", hjust = title_hjust, margin = margin(b = 2))
  )
cis <- ggplot(world_internet[,1:6], aes(fill = label, values = commonwealth)) +
  geom_waffle(
    nrows = 10, 
    flip = TRUE,
    show.legend = FALSE,
    color = "white",
    size = 0.5,
    radius = unit(2, "pt")) +
  labs(title = "CIS",
       caption = "73%") +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  scale_fill_manual(values = c("#ff7f00", "#d9d9d9"))+
  coord_equal() +
  theme(plot.caption= element_text(family = font, color = "#ff7f00", size = 10, face = "bold", hjust = caption_hjust, margin = margin(t = 5)),
    plot.title = element_text(family = font, color = text_color, size = 14, face = "bold", hjust = title_hjust, margin = margin(b = 2))
  )
europe <- ggplot(world_internet, aes(fill = label, values = europe)) +
  geom_waffle(
    nrows = 10, 
    flip = TRUE,
    show.legend = FALSE,
    color = "white",
    size = 0.5,
    radius = unit(2, "pt")) +
  labs(title = "Europe",
       caption = "83%") +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  scale_fill_manual(values = c("#e31a1c", "#d9d9d9"))+
  coord_equal() +
  theme(plot.caption= element_text(family = font, color = "#e31a1c", size = 10, face = "bold", hjust = caption_hjust, margin = margin(t = 5)),
    plot.title = element_text(family = font, color = text_color, size = 14, face = "bold", hjust = title_hjust, margin = margin(b = 2))
  )
plot_grid(africa, americas, arab, asia, cis, europe, ncol = 3)


